from setuptools import setup, find_packages

setup(
    name="MinimumActionDistance",
    version="0.1.0",
    description="MAD: Minimum Action Distance Metrics for Reinforcement Learning",
    author="Lorenzo Steccanella",
    author_email="lorenzo.steccanella.w@gmail.com",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "numpy~=2.2.2",
        "pygame~=2.6.1",
        "gymnasium~=1.3.0",
        "gymnasium-robotics~=1.4.2",
        "mujoco~=3.10.0",
        "ogbench~=1.2.1",
        "opencv-python~=5.0.0",
        "wandb~=0.19.4",
        "torch~=2.6.0",
        "tqdm~=4.67.1",
        "torchqmet @ git+https://github.com/quasimetric-learning/torch-quasimetric.git@0365394d4ecbd614f38775787af724d8b142c9d2",
        "matplotlib~=3.10.0",
        "tensordict~=0.7.2",
        "torchrl~=0.7.2",
        "scipy",
        "python-dotenv",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)
